name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    name: Test
    steps:
      - name: Install LLVM (Windows)
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "21"
